syntax = "proto3";
package blog;

service BlogService {
  rpc CreatePost(CreatePostRequest) returns (PostResponse);
  rpc GetPost(GetPostRequest) returns (PostResponse);
  rpc UpdatePost(UpdatePostRequest) returns (PostResponse);
  rpc DeletePost(DeletePostRequest) returns (Post);
  rpc ListPosts(ListPostsRequest) returns (ListPostsResponse);
}
message RegisterRequest {
  string login = 1;
  string password = 2;
  string name = 3;
}

message LoginRequest {
  string login = 1;
  string password = 2;
}

message CreatePostRequest {
  string userId = 1;
  string post = 2;
}

message GetPostRequest {
  string postId = 1;
}

message UpdatePostRequest {
  string postId = 1;
  string post = 2;
}

message DeletePostRequest {
  string postId = 1;
}

message AuthResponse {
  User user = 1;
}

message User {
  string id = 1;
  string login = 2;
  string name = 3;
  string email = 4;
}

message Post {
  string postId = 1;
  string headline = 2;
  string body = 3;
  string author = 4;
  string userId = 5;
}

message PostResponse {
  string postId = 1;
  string userId = 2;
}

message ListPostsRequest {
  int32 page = 1;
  int32 page_size = 2;
}

message ListPostsResponse {
  repeated Post posts = 1;
  int32 total_count = 2;
}